version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12

      - image: postgres:11
        environment:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: integration_test

    working_directory: ~/repo

    steps:
      - run: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      - run: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-11

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # 1. linting
      - run: yarn lint

      # 2. unit testing
      - run: yarn test:unit

      # 3. integration testing
      - run:
          command: yarn test:integration
          environment:
            DANGER_INTEGRATION_HOST: localhost
            DANGER_INTEGRATION_PORT: 5432
            DANGER_INTEGRATION_USER: testuser
            DANGER_INTEGRATION_PASSWORD: password
            DANGER_INTEGRATION_DATABASE: integration_test
            DANGER_INTEGRATION_RESET: nuke

